export default {
  // stacks
  AUTH_STACK: 'AUTH_STACK',
  APP_STACK: 'APP_STACK',

  //screens
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  HOME: 'HOME',
  RESTAURANT_DETAILS: 'RESTAURANT_DETAILS',
  USER_SELECTOR: 'USER_SELECTOR',
  EDIT_RESTAURANT: 'EDIT_RESTAURANT',
  NEW_REVIEW: 'NEW_REVIEW',
};
